<?php

use Illuminate\Database\Seeder;
use App\Models\ArticleCategory;
use App\Models\ArticleCategoryCrawlMapping;

class ArticleCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            [
                'category_name'=>'新闻',
                'category_priority'=>1000,
                'children'=>[
                    [
                        'category_name'=>'时政',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1460&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'国际',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1461&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'军事',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CHANNEL&sceneId=10&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'专题',
                        'category_enabled'=>false,
                    ],
                    [
                        'category_name'=>'公益',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/139?size=100&adapter=pc&secureScore=50&page=1',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'警法',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CHANNEL&sceneId=40&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'体育',
                'children'=>[
                    [
                        'category_name'=>'电竞',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4360?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'产业',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4280?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'高尔夫',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4282?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'乒乓球',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4287?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'帆船',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4281?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'排球',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4285?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'棋牌',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4289?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'跑步',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4286?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'拳击搏击',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4290?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'网球',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4293?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'羽毛球',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4298?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'台球',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4292?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'游泳',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4297?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'自行车',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4301?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],

                    ],
                    [
                        'category_name'=>'足球',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4364?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'赛车',
                        'crawl_mapping' => [
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/4291?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'旅游',
                'children'=>[
                    [
                        'category_name'=>'国内',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1446&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'境外',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/15156?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'攻略',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1448&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'签证',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=TAG&sceneId=69189&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'教育',
                'children'=>[
                    [
                        'category_name'=>'高考',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/10428?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'中小学',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/10431?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'高校',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/10430?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'留学',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/10433?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'考试',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/10432?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'时尚',
                'children'=>[
                    [
                        'category_name'=>'时装',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1045&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'奢品',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1057&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'美容',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1051&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'人物',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1062&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'男士',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1068&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'生活方式',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1073&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'娱乐',
                'children'=>[
                    [
                        'category_name'=>'明星八卦',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1406&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'电视剧',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1408&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'电影',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1409&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'综艺',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1410&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'科技',
                'children'=>[
                    [
                        'category_name'=>'互联网',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=911&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'通讯',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=934&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'智能硬件',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=882&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'生活服务',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=913&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'创业投资',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=881&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'科学',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://cis.sohu.com/cis/feeds?pvId=1&sceneParam=%5B%7B%22page%22%3A1%2C%22size%22%3A100%2C%22spm%22%3A%22smpc.column-5g.fd-news-1%22%7D%5D',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'smpc.column-5g.fd-news-1/data',
                                'item_key' => 'resourceData/contentData',
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'数码',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=936&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
            [
                'category_name'=>'文化',
                'children'=>[
                    [
                        'category_name'=>'人物',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/6343?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'读书',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/6345?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'艺术',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/6344?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'原创文学',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1404&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'地方文化',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/public-api/feed?scene=CATEGORY&sceneId=1403&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => null,
                                'item_key' => null,
                                'tags_key' => 'tags',
                                'tag_key' => null,
                                'tag' => 'name',
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => 'originalSource',
                                'article_description' => null,
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'picUrl',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => null,
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'影视',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/6279?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                    [
                        'category_name'=>'收藏',
                        'crawl_mapping'=>[
                            'target_host' => 'http://www.sohu.com',
                            'url'=>'http://v2.sohu.com/integration-api/mix/region/6280?adapter=pc&page=1&size=100',
                            'last_crawled_at' => null,
                            'mapping' => [
                                'list_key' => 'data',
                                'item_key' => null,
                                'tags_key' => null,
                                'tag_key' => null,
                                'tag' => null,
                                'article_title' => 'title',
                                'article_source' => 'authorName',
                                'article_source_link' => null,
                                'article_description' => 'brief',
                                'article_content' => '/(<article.*?<\/article>)/i',
                                'article_thumb' => 'cover',
                                'article_id' => ['id', '_', 'authorId'],
                                'article_base_url' => 'http://www.sohu.com/a/',
                                'article_url' => 'url',
                                'article_published_at' => 'publicTime',
                            ],
                        ],
                    ],
                ]
            ],
        ];

        foreach($categories as $category){
            $parentCategory = ArticleCategory::create(
                array_intersect_key($category, ['category_name'=>'', 'category_priority'=>''])
            );
            foreach($category['children'] as $subcat){
                $subcatModel = $parentCategory->subCategories()->create([
                    'category_name'=>$subcat['category_name'],
                    'category_enabled'=>array_key_exists('category_enabled', $subcat) ? $subcat['category_enabled'] : true,
                ]);
                if(array_key_exists('crawl_mapping', $subcat)){
                    $subcatModel->crawlMapping()->save(new ArticleCategoryCrawlMapping($subcat['crawl_mapping']));
                }
            }
        }
    }
}
